# Generated by Django 3.2.20 on 2023-09-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='pdf_documents/'),
        ),
    ]
