# Generated by Django 3.2.20 on 2023-12-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf_document_1',
            field=models.FileField(blank=True, null=True, upload_to='pdf_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pdf_document_2',
            field=models.FileField(blank=True, null=True, upload_to='pdf_documents/'),
        ),
    ]
