# Generated by Django 3.2.20 on 2023-12-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20231215_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_pdf',
            field=models.FileField(null=True, upload_to='pdf_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='third_pdf',
            field=models.FileField(null=True, upload_to='pdf_documents/'),
        ),
    ]
