# Generated by Django 3.2.20 on 2024-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('employee', 'Employee'), ('course', 'Course')], max_length=10),
        ),
    ]
