# Generated by Django 3.2.20 on 2024-01-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, choices=[('selected', 'Selected'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
