# Generated by Django 3.2.20 on 2024-01-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_alter_applicant_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='testimonial_images/')),
            ],
        ),
    ]
