# Generated by Django 3.2.20 on 2024-01-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0025_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='shift',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
