# Generated by Django 3.2.20 on 2024-01-31 19:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_alter_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='roomid',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
