# Generated by Django 3.2.20 on 2023-12-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20231212_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pdf_document_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pdf_document_2',
        ),
    ]
