# Generated by Django 3.2.20 on 2024-01-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=10, null=True),
        ),
    ]
