# Generated by Django 3.2.20 on 2024-01-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(default='free', max_length=50)),
                ('description', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='course_pdfs/')),
            ],
        ),
    ]
