# Generated by Django 3.2.20 on 2024-01-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0027_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
