# Generated by Django 3.2.20 on 2024-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0029_enrollment_roomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(choices=[('paid', 'Paid'), ('free', 'Free')], default='free', max_length=10),
        ),
    ]
