# Generated by Django 3.2.20 on 2024-02-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0033_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
