name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.projectKey=rmjob-project
        env:
          SONAR_HOST_URL: https://474f-103-129-135-38.ngrok-free.app
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Wait for SonarQube analysis to complete
        run: sleep 30

      - name: Check SonarQube Quality Gate status
        id: quality_gate
        run: |
          echo "Fetching the latest analysis ID from project_analyses/search..."

          # Retry for up to 10 times (total ~2 minutes) to avoid race conditions
          for i in {1..10}; do
            analysis_id=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
              "${{ env.SONAR_HOST_URL }}/api/project_analyses/search?project=rmjob-project" \
              | jq -r '.analyses[0].key')
          
            if [[ -n "$analysis_id" && "$analysis_id" != "null" ]]; then
              echo "Analysis ID found: $analysis_id"
              break
            else
              echo "Analysis ID not found yet (attempt $i). Retrying in 12 seconds..."
              sleep 12
            fi
          done
          
          if [[ -z "$analysis_id" || "$analysis_id" == "null" ]]; then
            echo "❌ Analysis ID not found after retries!"
            exit 1
          fi


          echo "Fetching the Quality Gate status..."
          status=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "${{ env.SONAR_HOST_URL }}/api/qualitygates/project_status?analysisId=$analysis_id" \
            | jq -r '.projectStatus.status')

          echo "Quality Gate status: $status"
          echo "quality_gate_status=$status" >> "$GITHUB_OUTPUT"

          if [[ "$status" != "OK" ]]; then
            echo "❌ Quality Gate failed!"
            exit 1
          else
            echo "✅ Quality Gate passed!"
          fi
        env:
          SONAR_HOST_URL: https://474f-103-129-135-38.ngrok-free.app

      - name: Send Slack Notification
        run: |
          status="${{ steps.quality_gate.outputs.quality_gate_status }}"
          if [[ "$status" == "OK" ]]; then
            message="✅ SonarQube Quality Gate passed for *${{ github.repository }}* on branch *${{ github.ref_name }}*"
          else
            message="❌ SonarQube Quality Gate failed for *${{ github.repository }}* on branch *${{ github.ref_name }}*"
          fi

          payload=$(jq -n \
            --arg text "$message" \
            '{text: $text}')

          curl -X POST -H 'Content-type: application/json' \
            --data "$payload" \
            "${{ secrets.SLACK_WEBHOOK_URL }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
