# .github/workflows/sonarqube.yml
name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.projectKey=my-repo
        env:
          SONAR_HOST_URL: https://636f-103-129-135-38.ngrok-free.app/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
